easy_admin:
    site_name: 'Firedev administration'
    list: 
        max_results: 10

    design:
        brand_color: '#1ABC9C'
        menu:
            # - { empty: 'Dashboard',  label: 'Dashboard', default: true } #route: 'homepage'
            - { entity: 'User', icon: 'user', label: 'Utilisateur' }
            - { entity: 'Groupe', icon: 'user', label: 'Groupe' }
            - { entity: 'Profil', icon: 'user', label: 'Profil' }
            - { entity: 'Langprog', icon: 'pencil', label: 'Language' }
            # - { entity: 'Document', icon: 'file', label: 'Document' }
            - { entity: 'Diplome', icon: 'tag', label: 'Diplomes' }
            - { entity: 'Projetrealiser', icon: 'tag', label: 'Projets' }
            - { entity: 'Experience', icon: 'tag', label: 'Experience' }
            - { entity: 'Annonce', icon: 'pencil', label: 'Annonces' }
            - { entity: 'News', icon: 'tag', label: 'News' }
            - { entity: 'Meslanguage', icon: 'pencil', label: 'Language par utilisateur' }
            - { entity: 'Projet', icon: 'pencil', label: 'Projets' }

    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - enabled
                    - username
                    - email
                    - lastLogin
                    - roles
                    - profil
            form:
                fields:
                    - username
                    - email
                    - enabled
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: false} }
                    # ...
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: true} }
                    # ...
                    # - { property: 'birthday',type: 'date', type_options: { widget: 'single_text'} }
                form_options: { validation_groups: ['Registration'] }
        Groupe:
            class: App\Entity\Groupe
                
        Profil:
            class: App\Entity\Profil
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - titre
                    - nom
                    - prenom
                    - { property: 'dateNais', type: 'birthday' ,label: 'Date de naissance' }
                    - { property: 'pays', type: 'country' }
                    - telephone
                    - adresse
                    - UserId
            list:
                fields:
                    - id
                    - titre
                    - nom
                    - prenom
                    - pays
                    - adresse
                    - { property: 'dateNais', label: 'Date de naissance' }
                    - { property: 'photo', label: 'photo', type: 'image', base_path: '%app.path.users_images%' }
                    - telephone
                    - { property: 'diplome', label: 'diplome' }
                    - { property: 'language', label: 'language' }
                    - { property: 'projetrealiser', label: 'projet' }
                    - UserId


        Annonce:
            class: App\Entity\Annonce
            form:
                fields:
                    - titre
                    - { property: 'imageFile', type: 'vich_image' }
                    #- explication
                    - { property: 'explication', type: 'ckeditor'}
                    - { property: 'degre', type: 'choice', type_options: { multiple: false, choices: { '1': 1, '2': 2, '3': 3 } } }
   
                    
            list:
                fields:
                    - id
                    - titre
                    - { property: 'image', type: 'image', base_path: '%app.path.annonce_images%' }
                    - explication
                    - degre     
            # show:
            #     fields:
            #         - id
            #         - titre
            #         - { property: 'image', type: 'image', base_path: '%app.path.annonce_images%' }
            #         - explication
            #         - degre
        News:
            class: App\Entity\News
            
        Langprog:
            class: App\Entity\Langprog
            form:
                fields:
                    - nom
                    - { property: 'imageFile', type: 'vich_image' }
                    - description
            list:
                fields:
                    - id
                    - nom
                    - { property: 'image', type: 'image', base_path: '%app.path.language_images%' }
                    - description
        # Document:
        #     class: App\Entity\Document

        Diplome:
            class: App\Entity\Diplome
        
        Projetrealiser:
            class: App\Entity\Projetrealiser

        Experience:
            class: App\Entity\Experience
        
        Meslanguage:
            class: App\Entity\Meslanguage
        
        Projet:
            class: App\Entity\Projet

