# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: parfait.onana50@gmail.com
        sender_name: Firedev Team
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
            from_email:
                address: parfait.onana50@gmail.com
                sender_name: Firedev Team
            # template:   '@FOSUser/Registration/email.txt.twig'
    resetting:
        email:
            from_email:
                address:        parfait.onana50@gmail.com
                sender_name:    Firedev Team
            # template:   emails/password_resetting.email.twig
    group:
        group_class: App\Entity\Groupe